+++
title = "Project Index"
layout = "single"
+++

== Internal

- Student Resource Index +
An "Awesome List" of various resources that can be helpful to LUG users and
UNISA students in general.
+
link:/projects/sri[PROJECT_PAGE]

== External

- The GARRistini project: a collaboration with GARRLab +
GARRLab is an informal community made up by an increasing number of technician
and students who are somehow related to GARR - our Italian NREN.
+
We have a very simple mandate: leveraging the bleeding-edge infrastructures
provided by GARR to foster our knowledge in a wide range of ICT technologies
(networking, system and network infrastructure management, 
cloud-based CI/CD git-assisted - aka: GitOps, system and network security,
…and lots of other things).
+
Our mission is simple: simplify our daily work (we, technicians) and put our
hands on top-knotch systems and equipments (we, students)
+
link:/projects/garristini[PROJECT_PAGE] |
https://garristini.garrlab.it[PROJECT_SITE]

== Historical

- Mokafeteria +
An implementation of an automation and management system for public refectories,
managed either by universities or private entities. +
The MVP must be able to replace the informatic systems of the main refectory of
the University of Salerno.
+
link:/projects/mokafeteria[PROJECT_PAGE]

== Proposals

- Data Preservation Network