+++
title = "Project Index"
layout = "single"
+++

== Internal

- link:sri[Student Resource Index] +
An "Awesome List" of various resources that can be helpful to LUG users and
UNISA students in general.

== External

- link:garristini[GARRistini] +
GARRistini is an initiatiative in collaboration with
link:https://www.garrlab.it[GARRLab],
born with the intention to form an informal community made up by an increasing
number of technician and academic students exploiting the resources of
link:https://garr.it[GARR: the Italian NREN].
+
We have a very simple mandate: +
leveraging the bleeding-edge infrastructures provided by GARR to foster our
knowledge in a wide range of ICT technologies like:
Networking, Infrastructure management, GitOps, Security, …and lots of other things.

== Historical

- link:mokafeteria[Mokafeteria] +
An implementation of an automation and management system for public refectories,
managed either by universities or private entities. +
The MVP must be able to replace the informatic systems of the main refectory of
the University of Salerno.

== Proposals

- Data Preservation Network