+++
title = "Association"
+++

IMPORTANT: The italian law mandates that a legally valid associaton must declare
a constitution act, a fundamental regulation document and a steering council. +
Nevertheless, given the current social situation, it hasn't been possible to
give course to the required proceedings. +
At the moment the founders have formed a temporary steering committee that
incorporates various roles in the association, until the coming of better times.

== The Board of Directors

The decisional core of the association. +
It's composed by the president, treasurer, secretary, community administrators,
community moderators. +
Right to partecipate is also given to executive honorary members and the
original founders, in the role of advisors.

=== Members

{{< directorsList.inline >}}
	{{ .Scratch.Set "memberListFilter_byRole" ( slice "Co-Director" ) }}
	{{ partial "memberCardList.html" . }}
{{< /directorsList.inline >}}

== The Community Council

It's a group of users interested in shaping the future of the community, it
includes the <<Board of Directors>>.

=== Members

{{< advisorsList.inline >}}
	{{ .Scratch.Set "memberListFilter_byRole" ( slice "Advisor" ) }}	
	{{ partial "memberCardList.html" . }}
{{< /advisorsList.inline >}}
