name: website
region: fra

domains:
- domain: lug.qub1750ul.me
  type: PRIMARY

static_sites:
- name: website
  routes:
  - path: /

  dockerfile_path: src/container/do-app-builder.dockerfile
  output_dir: /mnt/projectRoot/build/hugo

  github:
    repo: unisa-lug/website
    branch: main
    deploy_on_push: true
